import uuid
from typing import Literal, Union

from pydantic import BaseModel, Field
from backend.app.models.BaseValues import SkillRange, SoftSkills, HardSkills


class SoftSkill(BaseModel):
    """A soft skill with a validated proficiency level."""

    skill: Literal[SoftSkills]
    level: SkillRange
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique skill identifier, is generated by default.")

    class Config:
        frozen = True  # Skills should be immutable once created
        json_schema_extra = {
            "example": {
                "skill": "Communication",
                "level": 4.5,
            }
        }


class HardSkill(BaseModel):
    """A hard skill with a validated proficiency level."""

    skill: Literal[HardSkills]
    level: SkillRange
    experience: int = Field(..., description="Number of years of experience with this skill.", ge=0)
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique skill identifier, is generated by default.")

    class Config:
        frozen = True  # Skills should be immutable once created
        json_schema_extra = {
            "example": {
                "skill": "Communication",
                "level": 4.5,
                "experience": 2
            }
        }


# Union type for any skill
Skill = Union[SoftSkill, HardSkill]
